[package]
name = "xtask"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.45", features = ["derive"] }
clap_mangen = "0.2.29"
clap_complete = "4.5.57"
clap_complete_nushell = "4.5.8"

conductor = { path = "..", package = "cosmic-conductor" }
